name: bit_buffer
description: "A Dart library for efficient bit-level data manipulation, providing flexible reading and writing of various data types with configurable bit ordering."
version: 2.0.1
homepage: https://github.com/halifox/dart_bit_buffer

environment:
  sdk: ^3.6.0

dependencies:

dev_dependencies:
  test: 1.25.14