name: bit_buffer
description: "A new Flutter project."
version: 1.0.1
homepage: https://github.com/halifox/dart_bit_buffer

environment:
  sdk: ^3.6.0

dependencies:
  crypto: 3.0.6
  threshold: 1.0.4
dev_dependencies:
  test: 1.25.14