name: bit_buffer
description: "A new Flutter project."
version: 1.0.5
homepage: https://github.com/halifox/dart_bit_buffer

environment:
  sdk: ^3.6.0

dependencies:

dev_dependencies:
  test: 1.25.14